// <auto-generated />
using Formulario.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Formulario.Migrations
{
    [DbContext(typeof(FormularioContext))]
    partial class FormularioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Formulario.Model.Formacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Jugador1")
                        .HasColumnType("longtext");

                    b.Property<string>("Jugador10")
                        .HasColumnType("longtext");

                    b.Property<string>("Jugador11")
                        .HasColumnType("longtext");

                    b.Property<string>("Jugador2")
                        .HasColumnType("longtext");

                    b.Property<string>("Jugador3")
                        .HasColumnType("longtext");

                    b.Property<string>("Jugador4")
                        .HasColumnType("longtext");

                    b.Property<string>("Jugador5")
                        .HasColumnType("longtext");

                    b.Property<string>("Jugador6")
                        .HasColumnType("longtext");

                    b.Property<string>("Jugador7")
                        .HasColumnType("longtext");

                    b.Property<string>("Jugador8")
                        .HasColumnType("longtext");

                    b.Property<string>("Jugador9")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Formaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
